[AColorGroupSpectrumDG]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=48,48,48,#CGSAlpha#
 X=38
 Y=445
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ADarkGrey', 'ADarkGreyAlpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ADarkGreyButtons][!SetVariable AColorGroup "ADarkGrey"][!Update]

[AColorGroupSpectrumLG]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=119,119,119,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ALightGrey', 'ALightGreyAlpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ALightGreyButtons][!SetVariable AColorGroup "ALightGrey"][!Update]


[AColorGroupSpectrumR1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=218,0,37,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ARed1', 'ARed1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ARed1Buttons][!SetVariable AColorGroup "ARed1"][!Update]

[AColorGroupSpectrumR2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=240,24,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ARed2', 'ARed2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ARed2Buttons][!SetVariable AColorGroup "ARed2"][!Update]

[AColorGroupSpectrumO1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,67,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AOrange1', 'AOrange1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AOrange1Buttons][!SetVariable AColorGroup "AOrange1"][!Update]

[AColorGroupSpectrumO2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=253,108,5,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AOrange2', 'AOrange2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AOrange2Buttons][!SetVariable AColorGroup "AOrange2"][!Update]

[AColorGroupSpectrumY1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=254,171,7,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AYellow1', 'AYellow1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AYellow1Buttons][!SetVariable AColorGroup "AYellow1"][!Update]

[AColorGroupSpectrumY2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,201,30,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AYellow2', 'AYellow2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AYellow2Buttons][!SetVariable AColorGroup "AYellow2"][!Update]

[AColorGroupSpectrumGY]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=147,201,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AGreenYellow', 'AGreenYellowAlpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AGreenYellowButtons][!SetVariable AColorGroup "AGreenYellow"][!Update]

[AColorGroupSpectrumG1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=84,195,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AGreen1', 'AGreen1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AGreen1Buttons][!SetVariable AColorGroup "AGreen1"][!Update]

[AColorGroupSpectrumG2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,171,98,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('AGreen2', 'AGreen2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup AGreen2Buttons][!SetVariable AColorGroup "AGreen2"][!Update]

[AColorGroupSpectrumLB1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,195,196,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ALightBlue1', 'ALightBlue1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ALightBlue1Buttons][!SetVariable AColorGroup "ALightBlue1"][!Update]

[AColorGroupSpectrumLB2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,155,240,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ALightBlue2', 'ALightBlue2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ALightBlue2Buttons][!SetVariable AColorGroup "ALightBlue2"][!Update]

[AColorGroupSpectrumDB1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,106,254,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ADarkBlue1', 'ADarkBlue1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ADarkBlue1Buttons][!SetVariable AColorGroup "ADarkBlue1"][!Update]

[AColorGroupSpectrumDB2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=63,0,221,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('ADarkBlue2', 'ADarkBlue2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup ADarkBlue2Buttons][!SetVariable AColorGroup "ADarkBlue2"][!Update]

[AColorGroupSpectrumP1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=144,37,255,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('APink1', 'APink1Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup APink1Buttons][!SetVariable AColorGroup "APink1"][!Update]

[AColorGroupSpectrumP2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,62,194,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('APink2', 'APink2Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup APink2Buttons][!SetVariable AColorGroup "APink2"][!Update]

[AColorGroupSpectrumP3]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=254,11,107,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#AColorGroup#', '#AColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('APink3', 'APink3Alpha', 8)"][!HideMeterGroup #AColorGroup#Buttons][!ShowMeterGroup APink3Buttons][!SetVariable AColorGroup "APink3"][!Update]



;---OpenTab---
[AColorGroupSpectrumDGA]
 Meter=Image
 SolidColor=48,48,48,#ADarkGreyAlpha#
 X=38
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ADarkGrey
 UpdateDivider=-1

[AColorGroupSpectrumDGW]
 Meter=Image
 SolidColor=#BackgroundColor#,#ADarkGreyAlpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ADarkGrey
 UpdateDivider=-1


[AColorGroupSpectrumLGW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightGreyAlpha#
 X=51
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightGrey
 UpdateDivider=-1

[AColorGroupSpectrumLGA]
 Meter=Image
 SolidColor=119,119,119,#ALightGreyAlpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ALightGrey
 UpdateDivider=-1

[AColorGroupSpectrumLGW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightGreyAlpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightGrey
 UpdateDivider=-1


[AColorGroupSpectrumRW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ARed1Alpha#
 X=66
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ARed1
 UpdateDivider=-1

[AColorGroupSpectrumRA]
 Meter=Image
 SolidColor=218,0,37,#ARed1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ARed1
 UpdateDivider=-1

[AColorGroupSpectrumRW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ARed1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ARed1
 UpdateDivider=-1


[AColorGroupSpectrumR2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ARed2Alpha#
 X=81
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ARed2
 UpdateDivider=-1

[AColorGroupSpectrumR2A]
 Meter=Image
 SolidColor=240,24,0,#ARed2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ARed2
 UpdateDivider=-1

[AColorGroupSpectrumR2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ARed2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ARed2
 UpdateDivider=-1


[AColorGroupSpectrumOW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AOrange1Alpha#
 X=96
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AOrange1
 UpdateDivider=-1

[AColorGroupSpectrumOA]
 Meter=Image
 SolidColor=255,67,0,#AOrange1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AOrange1
 UpdateDivider=-1

[AColorGroupSpectrumOW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AOrange1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AOrange1
 UpdateDivider=-1


[AColorGroupSpectrumO2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AOrange2Alpha#
 X=111
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AOrange2
 UpdateDivider=-1

[AColorGroupSpectrumO2A]
 Meter=Image
 SolidColor=253,108,5,#AOrange2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AOrange2
 UpdateDivider=-1

[AColorGroupSpectrumO2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AOrange2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AOrange2
 UpdateDivider=-1


[AColorGroupSpectrumYW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AYellow1Alpha#
 X=126
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AYellow1
 UpdateDivider=-1

[AColorGroupSpectrumYA]
 Meter=Image
 SolidColor=254,171,7,#AYellow1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AYellow1
 UpdateDivider=-1

[AColorGroupSpectrumYW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AYellow1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AYellow1
 UpdateDivider=-1


[AColorGroupSpectrumY2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AYellow2Alpha#
 X=141
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AYellow2
 UpdateDivider=-1

[AColorGroupSpectrumY2A]
 Meter=Image
 SolidColor=255,201,30,#AYellow2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AYellow2
 UpdateDivider=-1

[AColorGroupSpectrumY2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AYellow2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AYellow2
 UpdateDivider=-1


[AColorGroupSpectrumGYW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreenYellowAlpha#
 X=156
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreenYellow
 UpdateDivider=-1

[AColorGroupSpectrumGYA]
 Meter=Image
 SolidColor=147,201,0,#AGreenYellowAlpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AGreenYellow
 UpdateDivider=-1

[AColorGroupSpectrumGYW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreenYellowAlpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreenYellow
 UpdateDivider=-1


[AColorGroupSpectrumGW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreen1Alpha#
 X=171
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreen1
 UpdateDivider=-1

[AColorGroupSpectrumGA]
 Meter=Image
 SolidColor=84,195,0,#AGreen1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AGreen1
 UpdateDivider=-1

[AColorGroupSpectrumGW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreen1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreen1
 UpdateDivider=-1


[AColorGroupSpectrumG2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreen2Alpha#
 X=186
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreen2
 UpdateDivider=-1

[AColorGroupSpectrumG2A]
 Meter=Image
 SolidColor=0,171,98,#AGreen2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=AGreen2
 UpdateDivider=-1

[AColorGroupSpectrumG2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#AGreen2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=AGreen2
 UpdateDivider=-1


[AColorGroupSpectrumLBW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightBlue1Alpha#
 X=201
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightBlue1
 UpdateDivider=-1

[AColorGroupSpectrumLBA]
 Meter=Image
 SolidColor=0,195,196,#ALightBlue1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ALightBlue1
 UpdateDivider=-1

[AColorGroupSpectrumLBW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightBlue1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightBlue1
 UpdateDivider=-1


[AColorGroupSpectrumLB2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightBlue2Alpha#
 X=219
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightBlue2
 UpdateDivider=-1

[AColorGroupSpectrumLB2A]
 Meter=Image
 SolidColor=0,155,240,#ALightBlue2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ALightBlue2
 UpdateDivider=-1

[AColorGroupSpectrumLB2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ALightBlue2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ALightBlue2
 UpdateDivider=-1


[AColorGroupSpectrumDBW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ADarkBlue1Alpha#
 X=231
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ADarkBlue1
 UpdateDivider=-1

[AColorGroupSpectrumDBA]
 Meter=Image
 SolidColor=0,106,254,#ADarkBlue1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ADarkBlue1
 UpdateDivider=-1

[AColorGroupSpectrumDBW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ADarkBlue1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ADarkBlue1
 UpdateDivider=-1


[AColorGroupSpectrumDB2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#ADarkBlue2Alpha#
 X=246
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ADarkBlue2
 UpdateDivider=-1

[AColorGroupSpectrumDB2A]
 Meter=Image
 SolidColor=63,0,221,#ADarkBlue2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=ADarkBlue2
 UpdateDivider=-1

[AColorGroupSpectrumDB2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#ADarkBlue2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=ADarkBlue2
 UpdateDivider=-1


[AColorGroupSpectrumPW1]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink1Alpha#
 X=261
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink1
 UpdateDivider=-1

[AColorGroupSpectrumPA]
 Meter=Image
 SolidColor=144,37,255,#APink1Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=APink1
 UpdateDivider=-1

[AColorGroupSpectrumPW2]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink1Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink1
 UpdateDivider=-1


[AColorGroupSpectrumP2W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink2Alpha#
 X=276
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink2
 UpdateDivider=-1

[AColorGroupSpectrumP2A]
 Meter=Image
 SolidColor=255,62,194,#APink2Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=APink2
 UpdateDivider=-1

[AColorGroupSpectrumP2W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink2Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink2
 UpdateDivider=-1


[AColorGroupSpectrumP3W1]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink3Alpha#
 X=291
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink3
 UpdateDivider=-1

[AColorGroupSpectrumP3A]
 Meter=Image
 SolidColor=254,11,107,#APink3Alpha#
 X=R
 Y=445
 W=13
 H=30
 DynamicVariables=1
 Group=APink3
 UpdateDivider=-1

[AColorGroupSpectrumP3W2]
 Meter=Image
 SolidColor=#BackgroundColor#,#APink3Alpha#
 X=R
 Y=445
 W=2
 H=20
 DynamicVariables=1
 Group=APink3
 UpdateDivider=-1