[ADarkGreyColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor1#,#ADarkGreyAlpha#
 X=38
 Y=353
 Group=ADarkGrey

[ADarkGreyColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor2#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor3#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor4#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor5#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor6#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor7#,#ADarkGreyAlpha#
 X=38
 Y=R
 Group=ADarkGrey

[ADarkGreyColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor8#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor9#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor10#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor11#,#ADarkGreyAlpha#
 Group=ADarkGrey

[ADarkGreyColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADGColor12#,#ADarkGreyAlpha#
 Group=ADarkGrey





;=====Buttons======
[ADarkGreyColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]

[ADarkGreyColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADGColor12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkGrey][!SetOption AColorCheck ImageAlpha #*ADarkGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADGColor12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkGrey][!WriteKeyValue AColorCheck ImageAlpha #*ADarkGreyAlpha*#]