[ADarkBlue1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color1#,#ADarkBlue1Alpha#
 X=38
 Y=353
 Group=ADarkBlue1

[ADarkBlue1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color2#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color3#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color4#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color5#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color6#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color7#,#ADarkBlue1Alpha#
 X=38
 Y=R
 Group=ADarkBlue1

[ADarkBlue1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color8#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color9#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color10#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color11#,#ADarkBlue1Alpha#
 Group=ADarkBlue1

[ADarkBlue1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB1Color12#,#ADarkBlue1Alpha#
 Group=ADarkBlue1





;=====Buttons======
[ADarkBlue1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]

[ADarkBlue1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue1][!SetOption AColorCheck ImageAlpha #*ADarkBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue1Alpha*#]