[ADarkBlue2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color1#,#ADarkBlue2Alpha#
 X=38
 Y=353
 Group=ADarkBlue2

[ADarkBlue2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color2#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color3#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color4#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color5#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color6#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color7#,#ADarkBlue2Alpha#
 X=38
 Y=R
 Group=ADarkBlue2

[ADarkBlue2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color8#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color9#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color10#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color11#,#ADarkBlue2Alpha#
 Group=ADarkBlue2

[ADarkBlue2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ADB2Color12#,#ADarkBlue2Alpha#
 Group=ADarkBlue2





;=====Buttons======
[ADarkBlue2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]

[ADarkBlue2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ADarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ADB2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ADarkBlue2][!SetOption AColorCheck ImageAlpha #*ADarkBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ADB2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ADarkBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ADarkBlue2Alpha*#]