[AGreenYellowColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor1#,#AGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AGreenYellow

[AGreenYellowColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor2#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor3#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor4#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor5#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor6#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor7#,#AGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AGreenYellow

[AGreenYellowColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor8#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor9#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor10#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor11#,#AGreenYellowAlpha#
 Group=AGreenYellow

[AGreenYellowColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AGYColor12#,#AGreenYellowAlpha#
 Group=AGreenYellow





;=====Buttons======
[AGreenYellowColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]

[AGreenYellowColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreenYellowButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#AGYColor12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreenYellow][!SetOption AColorCheck ImageAlpha #*AGreenYellowAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#AGYColor12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreenYellow][!WriteKeyValue AColorCheck ImageAlpha #*AGreenYellowAlpha*#]