[AGreen1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color1#,#AGreen1Alpha#
 X=38
 Y=353
 Group=AGreen1

[AGreen1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color2#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color3#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color4#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color5#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color6#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color7#,#AGreen1Alpha#
 X=38
 Y=R
 Group=AGreen1

[AGreen1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color8#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color9#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color10#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color11#,#AGreen1Alpha#
 Group=AGreen1

[AGreen1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG1Color12#,#AGreen1Alpha#
 Group=AGreen1





;=====Buttons======
[AGreen1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]

[AGreen1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen1][!SetOption AColorCheck ImageAlpha #*AGreen1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen1][!WriteKeyValue AColorCheck ImageAlpha #*AGreen1Alpha*#]