[AGreen2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color1#,#AGreen2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AGreen2

[AGreen2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color2#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color3#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color4#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color5#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color6#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color7#,#AGreen2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AGreen2

[AGreen2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color8#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color9#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color10#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color11#,#AGreen2Alpha#
 Group=AGreen2

[AGreen2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AG2Color12#,#AGreen2Alpha#
 Group=AGreen2





;=====Buttons======
[AGreen2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]

[AGreen2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AGreen2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AG2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AGreen2][!SetOption AColorCheck ImageAlpha #*AGreen2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AG2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AGreen2][!WriteKeyValue AColorCheck ImageAlpha #*AGreen2Alpha*#]