[ALightGreyColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor1#,#ALightGreyAlpha#
 X=38
 Y=353
 Group=ALightGrey

[ALightGreyColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor2#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor3#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor4#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor5#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor6#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor7#,#ALightGreyAlpha#
 X=38
 Y=R
 Group=ALightGrey

[ALightGreyColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor8#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor9#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor10#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor11#,#ALightGreyAlpha#
 Group=ALightGrey

[ALightGreyColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALGColor12#,#ALightGreyAlpha#
 Group=ALightGrey





;=====Buttons======
[ALightGreyColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]

[ALightGreyColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightGreyButtons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALGColor12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightGrey][!SetOption AColorCheck ImageAlpha #*ALightGreyAlpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALGColor12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightGrey][!WriteKeyValue AColorCheck ImageAlpha #*ALightGreyAlpha*#]