[ALightBlue2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color1#,#ALightBlue2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=ALightBlue2

[ALightBlue2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color2#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color3#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color4#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color5#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color6#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color7#,#ALightBlue2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=ALightBlue2

[ALightBlue2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color8#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color9#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color10#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color11#,#ALightBlue2Alpha#
 Group=ALightBlue2

[ALightBlue2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB2Color12#,#ALightBlue2Alpha#
 Group=ALightBlue2





;=====Buttons======
[ALightBlue2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]

[ALightBlue2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue2][!SetOption AColorCheck ImageAlpha #*ALightBlue2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue2][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue2Alpha*#]