[ALightBlue1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color1#,#ALightBlue1Alpha#
 X=38
 Y=353
 Group=ALightBlue1

[ALightBlue1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color2#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color3#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color4#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color5#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color6#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color7#,#ALightBlue1Alpha#
 X=38
 Y=R
 Group=ALightBlue1

[ALightBlue1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color8#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color9#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color10#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color11#,#ALightBlue1Alpha#
 Group=ALightBlue1

[ALightBlue1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#ALB1Color12#,#ALightBlue1Alpha#
 Group=ALightBlue1





;=====Buttons======
[ALightBlue1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]

[ALightBlue1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ALightBlue1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#ALB1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ALightBlue1][!SetOption AColorCheck ImageAlpha #*ALightBlue1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#ALB1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ALightBlue1][!WriteKeyValue AColorCheck ImageAlpha #*ALightBlue1Alpha*#]