[AOrange1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color1#,#AOrange1Alpha#
 X=38
 Y=353
 Group=AOrange1

[AOrange1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color2#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color3#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color4#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color5#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color6#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color7#,#AOrange1Alpha#
 X=38
 Y=R
 Group=AOrange1

[AOrange1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color8#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color9#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color10#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color11#,#AOrange1Alpha#
 Group=AOrange1

[AOrange1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO1Color12#,#AOrange1Alpha#
 Group=AOrange1





;=====Buttons======
[AOrange1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]

[AOrange1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange1][!SetOption AColorCheck ImageAlpha #*AOrange1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange1][!WriteKeyValue AColorCheck ImageAlpha #*AOrange1Alpha*#]