[AOrange2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color1#,#AOrange2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AOrange2

[AOrange2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color2#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color3#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color4#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color5#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color6#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color7#,#AOrange2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AOrange2

[AOrange2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color8#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color9#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color10#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color11#,#AOrange2Alpha#
 Group=AOrange2

[AOrange2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AO2Color12#,#AOrange2Alpha#
 Group=AOrange2





;=====Buttons======
[AOrange2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]

[AOrange2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AOrange2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AO2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AOrange2][!SetOption AColorCheck ImageAlpha #*AOrange2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AO2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AOrange2][!WriteKeyValue AColorCheck ImageAlpha #*AOrange2Alpha*#]