[APink1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color1#,#APink1Alpha#
 X=38
 Y=353
 Group=APink1

[APink1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color2#,#APink1Alpha#
 Group=APink1

[APink1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color3#,#APink1Alpha#
 Group=APink1

[APink1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color4#,#APink1Alpha#
 Group=APink1

[APink1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color5#,#APink1Alpha#
 Group=APink1

[APink1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color6#,#APink1Alpha#
 Group=APink1

[APink1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color7#,#APink1Alpha#
 X=38
 Y=R
 Group=APink1

[APink1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color8#,#APink1Alpha#
 Group=APink1

[APink1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color9#,#APink1Alpha#
 Group=APink1

[APink1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color10#,#APink1Alpha#
 Group=APink1

[APink1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color11#,#APink1Alpha#
 Group=APink1

[APink1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP1Color12#,#APink1Alpha#
 Group=APink1





;=====Buttons======
[APink1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]

[APink1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink1][!SetOption AColorCheck ImageAlpha #*APink1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink1][!WriteKeyValue AColorCheck ImageAlpha #*APink1Alpha*#]