[APink2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color1#,#APink2Alpha#
 X=38
 Y=353
 Group=APink2

[APink2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color2#,#APink2Alpha#
 Group=APink2

[APink2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color3#,#APink2Alpha#
 Group=APink2

[APink2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color4#,#APink2Alpha#
 Group=APink2

[APink2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color5#,#APink2Alpha#
 Group=APink2

[APink2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color6#,#APink2Alpha#
 Group=APink2

[APink2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color7#,#APink2Alpha#
 X=38
 Y=R
 Group=APink2

[APink2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color8#,#APink2Alpha#
 Group=APink2

[APink2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color9#,#APink2Alpha#
 Group=APink2

[APink2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color10#,#APink2Alpha#
 Group=APink2

[APink2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color11#,#APink2Alpha#
 Group=APink2

[APink2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP2Color12#,#APink2Alpha#
 Group=APink2





;=====Buttons======
[APink2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]

[APink2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink2][!SetOption AColorCheck ImageAlpha #*APink2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink2][!WriteKeyValue AColorCheck ImageAlpha #*APink2Alpha*#]