[APink3Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color1#,#APink3Alpha#
 X=38
 Y=353
 Group=APink3

[APink3Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color2#,#APink3Alpha#
 Group=APink3

[APink3Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color3#,#APink3Alpha#
 Group=APink3

[APink3Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color4#,#APink3Alpha#
 Group=APink3

[APink3Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color5#,#APink3Alpha#
 Group=APink3

[APink3Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color6#,#APink3Alpha#
 Group=APink3

[APink3Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color7#,#APink3Alpha#
 X=38
 Y=R
 Group=APink3

[APink3Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color8#,#APink3Alpha#
 Group=APink3

[APink3Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color9#,#APink3Alpha#
 Group=APink3

[APink3Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color10#,#APink3Alpha#
 Group=APink3

[APink3Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color11#,#APink3Alpha#
 Group=APink3

[APink3Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AP3Color12#,#APink3Alpha#
 Group=APink3





;=====Buttons======
[APink3Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=353
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]

[APink3Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=APink3Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AP3Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup APink3][!SetOption AColorCheck ImageAlpha #*APink3Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AP3Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup APink3][!WriteKeyValue AColorCheck ImageAlpha #*APink3Alpha*#]