[ARed1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color1#,#ARed1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=ARed1

[ARed1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color2#,#ARed1Alpha#
 Group=ARed1

[ARed1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color3#,#ARed1Alpha#
 Group=ARed1

[ARed1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color4#,#ARed1Alpha#
 Group=ARed1

[ARed1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color5#,#ARed1Alpha#
 Group=ARed1

[ARed1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color6#,#ARed1Alpha#
 Group=ARed1

[ARed1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color7#,#ARed1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=ARed1

[ARed1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color8#,#ARed1Alpha#
 Group=ARed1

[ARed1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color9#,#ARed1Alpha#
 Group=ARed1

[ARed1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color10#,#ARed1Alpha#
 Group=ARed1

[ARed1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color11#,#ARed1Alpha#
 Group=ARed1

[ARed1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AR1Color12#,#ARed1Alpha#
 Group=ARed1





;=====Buttons======
[ARed1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]

[ARed1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=ARed1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AR1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup ARed1][!SetOption AColorCheck ImageAlpha #*ARed1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AR1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup ARed1][!WriteKeyValue AColorCheck ImageAlpha #*ARed1Alpha*#]