[AYellow2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color1#,#AYellow2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AYellow2

[AYellow2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color2#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color3#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color4#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color5#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color6#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color7#,#AYellow2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AYellow2

[AYellow2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color8#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color9#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color10#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color11#,#AYellow2Alpha#
 Group=AYellow2

[AYellow2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY2Color12#,#AYellow2Alpha#
 Group=AYellow2





;=====Buttons======
[AYellow2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]

[AYellow2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow2Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY2Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow2][!SetOption AColorCheck ImageAlpha #*AYellow2Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow2][!WriteKeyValue AColorCheck ImageAlpha #*AYellow2Alpha*#]