[AYellow1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color1#,#AYellow1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AYellow1

[AYellow1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color2#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color3#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color4#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color5#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color6#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color7#,#AYellow1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AYellow1

[AYellow1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color8#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color9#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color10#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color11#,#AYellow1Alpha#
 Group=AYellow1

[AYellow1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#AY1Color12#,#AYellow1Alpha#
 Group=AYellow1





;=====Buttons======
[AYellow1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=353
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color1#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color2#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color3#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color4#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color5#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color6#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 1][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 1][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color7#"][!SetVariable AColorRow 1][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 1][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color8#"][!SetVariable AColorRow 2][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 2][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color9#"][!SetVariable AColorRow 3][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 3][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color10#"][!SetVariable AColorRow 4][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 4][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color11#"][!SetVariable AColorRow 5][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 5][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#]

[AYellow1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=AYellow1Buttons
 LeftMouseUpAction=[!SetVariable AccentColor "#AY1Color12#"][!SetVariable AColorRow 6][!SetVariable AColorColumn 2][!SetVariable AColorCheckGroup AYellow1][!SetOption AColorCheck ImageAlpha #*AYellow1Alpha*#][!Update][!WriteKeyValue Variables AccentColor "#AY1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables AColorRow 6][!WriteKeyValue Variables AColorColumn 2][!WriteKeyValue Variables AColorCheckGroup AYellow1][!WriteKeyValue AColorCheck ImageAlpha #*AYellow1Alpha*#] 