[BGColorGroupSpectrumDG]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=48,48,48,#CGSAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=265
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGDarkGrey', 'BGDarkGreyAlpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGDarkGreyButtons][!SetVariable BGColorGroup "BGDarkGrey"][!Update]

[BGColorGroupSpectrumLG]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=119,119,119,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGLightGrey', 'BGLightGreyAlpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGLightGreyButtons][!SetVariable BGColorGroup "BGLightGrey"][!Update]

[BGColorGroupSpectrumR1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=218,0,37,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGRed1', 'BGRed1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGRed1Buttons][!SetVariable BGColorGroup "BGRed1"][!Update]

[BGColorGroupSpectrumR2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=240,24,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGRed2', 'BGRed2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGRed2Buttons][!SetVariable BGColorGroup "BGRed2"][!Update]

[BGColorGroupSpectrumO1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,67,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGOrange1', 'BGOrange1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGOrange1Buttons][!SetVariable BGColorGroup "BGOrange1"][!Update]

[BGColorGroupSpectrumO2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=253,108,5,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGOrange2', 'BGOrange2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGOrange2Buttons][!SetVariable BGColorGroup "BGOrange2"][!Update]

[BGColorGroupSpectrumY1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=254,171,7,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGYellow1', 'BGYellow1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGYellow1Buttons][!SetVariable BGColorGroup "BGYellow1"][!Update]

[BGColorGroupSpectrumY2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,201,30,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGYellow2', 'BGYellow2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGYellow2Buttons][!SetVariable BGColorGroup "BGYellow2"][!Update]

[BGColorGroupSpectrumGY]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=147,201,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGGreenYellow', 'BGGreenYellowAlpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGGreenYellowButtons][!SetVariable BGColorGroup "BGGreenYellow"][!Update]



[BGColorGroupSpectrumG1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=84,195,0,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGGreen1', 'BGGreen1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGGreen1Buttons][!SetVariable BGColorGroup "BGGreen1"][!Update]

[BGColorGroupSpectrumG2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,171,98,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGGreen2', 'BGGreen2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGGreen2Buttons][!SetVariable BGColorGroup "BGGreen2"][!Update]

[BGColorGroupSpectrumLB1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,195,196,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGLightBlue1', 'BGLightBlue1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGLightBlue1Buttons][!SetVariable BGColorGroup "BGLightBlue1"][!Update]

[BGColorGroupSpectrumLB2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,155,240,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGLightBlue2', 'BGLightBlue2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGLightBlue2Buttons][!SetVariable BGColorGroup "BGLightBlue2"][!Update]

[BGColorGroupSpectrumDB1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=0,106,254,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGDarkBlue1', 'BGDarkBlue1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGDarkBlue1Buttons][!SetVariable BGColorGroup "BGDarkBlue1"][!Update]

[BGColorGroupSpectrumDB2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=63,0,221,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGDarkBlue2', 'BGDarkBlue2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGDarkBlue2Buttons][!SetVariable BGColorGroup "BGDarkBlue2"][!Update]

[BGColorGroupSpectrumP1]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=144,37,255,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGPink1', 'BGPink1Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGPink1Buttons][!SetVariable BGColorGroup "BGPink1"][!Update]

[BGColorGroupSpectrumP2]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=255,62,194,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGPink2', 'BGPink2Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGPink2Buttons][!SetVariable BGColorGroup "BGPink2"][!Update]

[BGColorGroupSpectrumP3]
 Meter=Image
 MeterStyle=ColorGroupStyle
 SolidColor=254,11,107,#CGSAlpha#
 LeftMouseUpAction=[!CommandMeasure Transition "FadeOut('#BGColorGroup#', '#BGColorGroup#Alpha', 10)"][!CommandMeasure Transition "FadeIn('BGPink3', 'BGPink3Alpha', 8)"][!HideMeterGroup #BGColorGroup#Buttons][!ShowMeterGroup BGPink3Buttons][!SetVariable BGColorGroup "BGPink3"][!Update]



;---OpenTab---
[BGColorGroupSpectrumDGA]
 Meter=Image
 SolidColor=48,48,48,#BGDarkGreyAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGDarkGrey
 UpdateDivider=10

[BGColorGroupSpectrumDGW]
 Meter=Image
 SolidColor=255,255,255,#BGDarkGreyAlpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGDarkGrey
 UpdateDivider=10


[BGColorGroupSpectrumLGW1]
 Meter=Image
 SolidColor=255,255,255,#BGLightGreyAlpha#
 X=(#WORKAREAWIDTH#-294)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightGrey
 UpdateDivider=10

[BGColorGroupSpectrumLGA]
 Meter=Image
 SolidColor=119,119,119,#BGLightGreyAlpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGLightGrey
 UpdateDivider=10

[BGColorGroupSpectrumLGW2]
 Meter=Image
 SolidColor=255,255,255,#BGLightGreyAlpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightGrey
 UpdateDivider=10


[BGColorGroupSpectrumRW1]
 Meter=Image
 SolidColor=255,255,255,#BGRed1Alpha#
 X=(#WORKAREAWIDTH#-279)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGRed1
 UpdateDivider=10

[BGColorGroupSpectrumRA]
 Meter=Image
 SolidColor=218,0,37,#BGRed1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGRed1
 UpdateDivider=10

[BGColorGroupSpectrumRW2]
 Meter=Image
 SolidColor=255,255,255,#BGRed1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGRed1
 UpdateDivider=10


[BGColorGroupSpectrumR2W1]
 Meter=Image
 SolidColor=255,255,255,#BGRed2Alpha#
 X=(#WORKAREAWIDTH#-264)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGRed2
 UpdateDivider=10

[BGColorGroupSpectrumR2A]
 Meter=Image
 SolidColor=240,24,0,#BGRed2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGRed2
 UpdateDivider=10

[BGColorGroupSpectrumR2W2]
 Meter=Image
 SolidColor=255,255,255,#BGRed2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGRed2
 UpdateDivider=10


[BGColorGroupSpectrumOW1]
 Meter=Image
 SolidColor=255,255,255,#BGOrange1Alpha#
 X=(#WORKAREAWIDTH#-249)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGOrange1
 UpdateDivider=10

[BGColorGroupSpectrumOA]
 Meter=Image
 SolidColor=255,67,0,#BGOrange1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGOrange1
 UpdateDivider=10

[BGColorGroupSpectrumOW2]
 Meter=Image
 SolidColor=255,255,255,#BGOrange1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGOrange1
 UpdateDivider=10


[BGColorGroupSpectrumO2W1]
 Meter=Image
 SolidColor=255,255,255,#BGOrange2Alpha#
 X=(#WORKAREAWIDTH#-234)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGOrange2
 UpdateDivider=10

[BGColorGroupSpectrumO2A]
 Meter=Image
 SolidColor=253,108,5,#BGOrange2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGOrange2
 UpdateDivider=10

[BGColorGroupSpectrumO2W2]
 Meter=Image
 SolidColor=255,255,255,#BGOrange2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGOrange2
 UpdateDivider=10


[BGColorGroupSpectrumYW1]
 Meter=Image
 SolidColor=255,255,255,#BGYellow1Alpha#
 X=(#WORKAREAWIDTH#-219)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGYellow1
 UpdateDivider=10

[BGColorGroupSpectrumYA]
 Meter=Image
 SolidColor=254,171,7,#BGYellow1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGYellow1
 UpdateDivider=10

[BGColorGroupSpectrumYW2]
 Meter=Image
 SolidColor=255,255,255,#BGYellow1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGYellow1
 UpdateDivider=10


[BGColorGroupSpectrumY2W1]
 Meter=Image
 SolidColor=255,255,255,#BGYellow2Alpha#
 X=(#WORKAREAWIDTH#-204)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGYellow2
 UpdateDivider=10

[BGColorGroupSpectrumY2A]
 Meter=Image
 SolidColor=255,201,30,#BGYellow2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGYellow2
 UpdateDivider=10

[BGColorGroupSpectrumY2W2]
 Meter=Image
 SolidColor=255,255,255,#BGYellow2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGYellow2
 UpdateDivider=10


[BGColorGroupSpectrumGYW1]
 Meter=Image
 SolidColor=255,255,255,#BGGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-189)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreenYellow
 UpdateDivider=10

[BGColorGroupSpectrumGYA]
 Meter=Image
 SolidColor=147,201,0,#BGGreenYellowAlpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGGreenYellow
 UpdateDivider=10

[BGColorGroupSpectrumGYW2]
 Meter=Image
 SolidColor=255,255,255,#BGGreenYellowAlpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreenYellow
 UpdateDivider=10


[BGColorGroupSpectrumGW1]
 Meter=Image
 SolidColor=255,255,255,#BGGreen1Alpha#
 X=(#WORKAREAWIDTH#-174)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreen1
 UpdateDivider=10

[BGColorGroupSpectrumGA]
 Meter=Image
 SolidColor=84,195,0,#BGGreen1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGGreen1
 UpdateDivider=10

[BGColorGroupSpectrumGW2]
 Meter=Image
 SolidColor=255,255,255,#BGGreen1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreen1
 UpdateDivider=10


[BGColorGroupSpectrumG2W1]
 Meter=Image
 SolidColor=255,255,255,#BGGreen2Alpha#
 X=(#WORKAREAWIDTH#-159)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreen2
 UpdateDivider=10

[BGColorGroupSpectrumG2A]
 Meter=Image
 SolidColor=0,171,98,#BGGreen2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGGreen2
 UpdateDivider=10

[BGColorGroupSpectrumG2W2]
 Meter=Image
 SolidColor=255,255,255,#BGGreen2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGGreen2
 UpdateDivider=10


[BGColorGroupSpectrumLBW1]
 Meter=Image
 SolidColor=255,255,255,#BGLightBlue1Alpha#
 X=(#WORKAREAWIDTH#-144)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightBlue1
 UpdateDivider=10

[BGColorGroupSpectrumLBA]
 Meter=Image
 SolidColor=0,195,196,#BGLightBlue1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGLightBlue1
 UpdateDivider=10

[BGColorGroupSpectrumLBW2]
 Meter=Image
 SolidColor=255,255,255,#BGLightBlue1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightBlue1
 UpdateDivider=10


[BGColorGroupSpectrumLB2W1]
 Meter=Image
 SolidColor=255,255,255,#BGLightBlue2Alpha#
 X=(#WORKAREAWIDTH#-129)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightBlue2
 UpdateDivider=10

[BGColorGroupSpectrumLB2A]
 Meter=Image
 SolidColor=0,155,240,#BGLightBlue2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGLightBlue2
 UpdateDivider=10

[BGColorGroupSpectrumLB2W2]
 Meter=Image
 SolidColor=255,255,255,#BGLightBlue2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGLightBlue2
 UpdateDivider=10


[BGColorGroupSpectrumDBW1]
 Meter=Image
 SolidColor=255,255,255,#BGDarkBlue1Alpha#
 X=(#WORKAREAWIDTH#-114)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGDarkBlue1
 UpdateDivider=10

[BGColorGroupSpectrumDBA]
 Meter=Image
 SolidColor=0,106,254,#BGDarkBlue1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGDarkBlue1
 UpdateDivider=10

[BGColorGroupSpectrumDBW2]
 Meter=Image
 SolidColor=255,255,255,#BGDarkBlue1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGDarkBlue1
 UpdateDivider=10


[BGColorGroupSpectrumDB2W1]
 Meter=Image
 SolidColor=255,255,255,#BGDarkBlue2Alpha#
 X=(#WORKAREAWIDTH#-99)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGDarkBlue2
 UpdateDivider=10

[BGColorGroupSpectrumDB2A]
 Meter=Image
 SolidColor=63,0,221,#BGDarkBlue2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGDarkBlue2
 UpdateDivider=10

[BGColorGroupSpectrumDB2W2]
 Meter=Image
 SolidColor=255,255,255,#BGDarkBlue2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGDarkBlue2
 UpdateDivider=10


[BGColorGroupSpectrumPW1]
 Meter=Image
 SolidColor=255,255,255,#BGPink1Alpha#
 X=(#WORKAREAWIDTH#-84)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink1
 UpdateDivider=10

[BGColorGroupSpectrumPA]
 Meter=Image
 SolidColor=144,37,255,#BGPink1Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGPink1
 UpdateDivider=10

[BGColorGroupSpectrumPW2]
 Meter=Image
 SolidColor=255,255,255,#BGPink1Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink1
 UpdateDivider=10


[BGColorGroupSpectrumP2W1]
 Meter=Image
 SolidColor=255,255,255,#BGPink2Alpha#
 X=(#WORKAREAWIDTH#-69)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink2
 UpdateDivider=10

[BGColorGroupSpectrumP2A]
 Meter=Image
 SolidColor=255,62,194,#BGPink2Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGPink2
 UpdateDivider=10

[BGColorGroupSpectrumP2W2]
 Meter=Image
 SolidColor=255,255,255,#BGPink2Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink2
 UpdateDivider=10


[BGColorGroupSpectrumP3W1]
 Meter=Image
 SolidColor=255,255,255,#BGPink3Alpha#
 X=(#WORKAREAWIDTH#-54)
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink3
 UpdateDivider=10

[BGColorGroupSpectrumP3A]
 Meter=Image
 SolidColor=254,11,107,#BGPink3Alpha#
 X=R
 Y=265
 W=13
 H=30
 DynamicVariables=1
 Group=BGPink3
 UpdateDivider=10

[BGColorGroupSpectrumP3W2]
 Meter=Image
 SolidColor=255,255,255,#BGPink3Alpha#
 X=R
 Y=265
 W=2
 H=20
 DynamicVariables=1
 Group=BGPink3
 UpdateDivider=10