[BGDarkGreyColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor1#,#BGDarkGreyAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGDarkGrey

[BGDarkGreyColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor2#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor3#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor4#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor5#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor6#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor7#,#BGDarkGreyAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkGrey

[BGDarkGreyColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor8#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor9#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor10#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor11#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor12#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor13#,#BGDarkGreyAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkGrey

[BGDarkGreyColor14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor14#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor15#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor16#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor17#,#BGDarkGreyAlpha#
 Group=BGDarkGrey

[BGDarkGreyColor18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDGColor18#,#BGDarkGreyAlpha#
 Group=BGDarkGrey



;=====Buttons=====
[BGDarkGreyColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor6]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]

[BGDarkGreyColor18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDGColor18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkGrey][!SetOption BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDGColor18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkGreyAlpha*#]