[BGDarkBlue2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color1#,#BGDarkBlue2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGDarkBlue2

[BGDarkBlue2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color2#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color3#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color4#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color5#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color6#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color7#,#BGDarkBlue2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkBlue2

[BGDarkBlue2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color8#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color9#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color10#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color11#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color12#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color13#,#BGDarkBlue2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkBlue2

[BGDarkBlue2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color14#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color15#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color16#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color17#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2

[BGDarkBlue2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB2Color18#,#BGDarkBlue2Alpha#
 Group=BGDarkBlue2



 ;=====Buttons=====
 [BGDarkBlue2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]

[BGDarkBlue2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue2][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue2Alpha*#]