[BGDarkBlue1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color1#,#BGDarkBlue1Alpha#
 X=38
 Y=128
 Group=BGDarkBlue1

[BGDarkBlue1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color2#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color3#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color4#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color5#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color6#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color7#,#BGDarkBlue1Alpha#
 X=38
 Y=R
 Group=BGDarkBlue1

[BGDarkBlue1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color8#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color9#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color10#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color11#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color12#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color13#,#BGDarkBlue1Alpha#
 X=38
 Y=R
 Group=BGDarkBlue1

[BGDarkBlue1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color14#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color15#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color16#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color17#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1

[BGDarkBlue1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGDB1Color18#,#BGDarkBlue1Alpha#
 Group=BGDarkBlue1



 ;=====Buttons=====
 [BGDarkBlue1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]

[BGDarkBlue1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGDarkBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGDB1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGDarkBlue1][!SetOption BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGDB1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGDarkBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGDarkBlue1Alpha*#]