[BGGreen1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color1#,#BGGreen1Alpha#
 X=38
 Y=128
 Group=BGGreen1

[BGGreen1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color2#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color3#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color4#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color5#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color6#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color7#,#BGGreen1Alpha#
 X=38
 Y=R
 Group=BGGreen1

[BGGreen1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color8#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color9#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color10#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color11#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color12#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color13#,#BGGreen1Alpha#
 X=38
 Y=R
 Group=BGGreen1

[BGGreen1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color14#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color15#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color16#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color17#,#BGGreen1Alpha#
 Group=BGGreen1

[BGGreen1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG1Color18#,#BGGreen1Alpha#
 Group=BGGreen1




 ;=====Buttons=====
 [BGGreen1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]

[BGGreen1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen1][!SetOption BGColorCheck ImageAlpha #*BGGreen1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen1][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen1Alpha*#]