[BGGreenYellowColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor1#,#BGGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGGreenYellow

[BGGreenYellowColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor2#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor3#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor4#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor5#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor6#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor7#,#BGGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGGreenYellow

[BGGreenYellowColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor8#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor9#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor10#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor11#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor12#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor13#,#BGGreenYellowAlpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGGreenYellow

[BGGreenYellowColor14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor14#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor15#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor16#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor17#,#BGGreenYellowAlpha#
 Group=BGGreenYellow

[BGGreenYellowColor18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGGYColor18#,#BGGreenYellowAlpha#
 Group=BGGreenYellow




;=====Buttons=====
[BGGreenYellowColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]

[BGGreenYellowColor18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreenYellowButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGGYColor18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreenYellow][!SetOption BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGGYColor18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreenYellow][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreenYellowAlpha*#]