[BGGreen2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color1#,#BGGreen2Alpha#
 X=38
 Y=128
 Group=BGGreen2

[BGGreen2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color2#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color3#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color4#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color5#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color6#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color7#,#BGGreen2Alpha#
 X=38
 Y=R
 Group=BGGreen2

[BGGreen2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color8#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color9#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color10#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color11#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color12#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color13#,#BGGreen2Alpha#
 X=38
 Y=R
 Group=BGGreen2

[BGGreen2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color14#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color15#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color16#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color17#,#BGGreen2Alpha#
 Group=BGGreen2

[BGGreen2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGG2Color18#,#BGGreen2Alpha#
 Group=BGGreen2




;=====Buttons=====
[BGGreen2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]

[BGGreen2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGGreen2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGG2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGGreen2][!SetOption BGColorCheck ImageAlpha #*BGGreen2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGG2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGGreen2][!WriteKeyValue BGColorCheck ImageAlpha #*BGGreen2Alpha*#]