[BGLightBlue2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color1#,#BGLightBlue2Alpha#
 X=38
 Y=128
 Group=BGLightBlue2

[BGLightBlue2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color2#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color3#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color4#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color5#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color6#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color7#,#BGLightBlue2Alpha#
 X=38
 Y=R
 Group=BGLightBlue2

[BGLightBlue2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color8#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color9#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color10#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color11#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color12#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color13#,#BGLightBlue2Alpha#
 X=38
 Y=R
 Group=BGLightBlue2

[BGLightBlue2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color14#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color15#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color16#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color17#,#BGLightBlue2Alpha#
 Group=BGLightBlue2

[BGLightBlue2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB2Color18#,#BGLightBlue2Alpha#
 Group=BGLightBlue2




;=====Buttons=====
[BGLightBlue2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]

[BGLightBlue2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue2][!SetOption BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue2][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue2Alpha*#]