[BGLightGreyColor1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor1#,#BGLightGreyAlpha#
 X=38
 Y=128
 Group=BGLightGrey

[BGLightGreyColor2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor2#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor3#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor4#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor5#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor6#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor7#,#BGLightGreyAlpha#
 X=38
 Y=R
 Group=BGLightGrey

[BGLightGreyColor8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor8#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor9#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor10#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor11#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor12#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor13#,#BGLightGreyAlpha#
 X=38
 Y=R
 Group=BGLightGrey

[BGLightGreyColor14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor14#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor15#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor16#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor17#,#BGLightGreyAlpha#
 Group=BGLightGrey

[BGLightGreyColor18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLGColor18#,#BGLightGreyAlpha#
 Group=BGLightGrey




;=====Buttons=====
[BGLightGreyColor1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]

[BGLightGreyColor18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightGreyButtons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLGColor18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightGrey][!SetOption BGColorCheck ImageAlpha #*BGLightGreyAlpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLGColor18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightGrey][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightGreyAlpha*#]