[BGLightBlue1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color1#,#BGLightBlue1Alpha#
 X=38
 Y=128
 Group=BGLightBlue1

[BGLightBlue1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color2#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color3#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color4#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color5#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color6#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color7#,#BGLightBlue1Alpha#
 X=38
 Y=R
 Group=BGLightBlue1

[BGLightBlue1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color8#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color9#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color10#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color11#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color12#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color13#,#BGLightBlue1Alpha#
 X=38
 Y=R
 Group=BGLightBlue1

[BGLightBlue1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color14#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color15#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color16#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color17#,#BGLightBlue1Alpha#
 Group=BGLightBlue1

[BGLightBlue1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGLB1Color18#,#BGLightBlue1Alpha#
 Group=BGLightBlue1




;=====Buttons=====
[BGLightBlue1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]

[BGLightBlue1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGLightBlue1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGLB1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGLightBlue1][!SetOption BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGLB1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGLightBlue1][!WriteKeyValue BGColorCheck ImageAlpha #*BGLightBlue1Alpha*#]