[BGOrange1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color1#,#BGOrange1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGOrange1

[BGOrange1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color2#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color3#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color4#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color5#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color6#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color7#,#BGOrange1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGOrange1

[BGOrange1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color8#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color9#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color10#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color11#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color12#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color13#,#BGOrange1Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGOrange1

[BGOrange1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color14#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color15#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color16#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color17#,#BGOrange1Alpha#
 Group=BGOrange1

[BGOrange1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO1Color18#,#BGOrange1Alpha#
 Group=BGOrange1




;=====Buttons=====
[BGOrange1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]

[BGOrange1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange1][!SetOption BGColorCheck ImageAlpha #*BGOrange1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange1][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange1Alpha*#]