[BGOrange2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color1#,#BGOrange2Alpha#
 X=38
 Y=128
 Group=BGOrange2

[BGOrange2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color2#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color3#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color4#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color5#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color6#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color7#,#BGOrange2Alpha#
 X=38
 Y=R
 Group=BGOrange2

[BGOrange2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color8#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color9#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color10#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color11#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color12#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color13#,#BGOrange2Alpha#
 X=38
 Y=R
 Group=BGOrange2

[BGOrange2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color14#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color15#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color16#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color17#,#BGOrange2Alpha#
 Group=BGOrange2

[BGOrange2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGO2Color18#,#BGOrange2Alpha#
 Group=BGOrange2




;=====Buttons=====
[BGOrange2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]

[BGOrange2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGOrange2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGO2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGOrange2][!SetOption BGColorCheck ImageAlpha #*BGOrange2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGO2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGOrange2][!WriteKeyValue BGColorCheck ImageAlpha #*BGOrange2Alpha*#]