[BGPink2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color1#,#BGPink2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGPink2

[BGPink2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color2#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color3#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color4#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color5#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color6#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color7#,#BGPink2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGPink2

[BGPink2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color8#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color9#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color10#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color11#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color12#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color13#,#BGPink2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGPink2

[BGPink2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color14#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color15#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color16#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color17#,#BGPink2Alpha#
 Group=BGPink2

[BGPink2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP2Color18#,#BGPink2Alpha#
 Group=BGPink2




;=====Buttons=====
[BGPink2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]

[BGPink2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink2][!SetOption BGColorCheck ImageAlpha #*BGPink2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink2][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink2Alpha*#]