[BGPink1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color1#,#BGPink1Alpha#
 X=38
 Y=128
 Group=BGPink1

[BGPink1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color2#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color3#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color4#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color5#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color6#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color7#,#BGPink1Alpha#
 X=38
 Y=R
 Group=BGPink1

[BGPink1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color8#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color9#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color10#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color11#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color12#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color13#,#BGPink1Alpha#
 X=38
 Y=R
 Group=BGPink1

[BGPink1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color14#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color15#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color16#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color17#,#BGPink1Alpha#
 Group=BGPink1

[BGPink1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP1Color18#,#BGPink1Alpha#
 Group=BGPink1





;=====Buttons=====
[BGPink1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]

[BGPink1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink1][!SetOption BGColorCheck ImageAlpha #*BGPink1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink1][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink1Alpha*#]