[BGPink3Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color1#,#BGPink3Alpha#
 X=38
 Y=128
 Group=BGPink3

[BGPink3Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color2#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color3#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color4#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color5#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color6#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color7#,#BGPink3Alpha#
 X=38
 Y=R
 Group=BGPink3

[BGPink3Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color8#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color9#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color10#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color11#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color12#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color13#,#BGPink3Alpha#
 X=38
 Y=R
 Group=BGPink3

[BGPink3Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color14#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color15#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color16#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color17#,#BGPink3Alpha#
 Group=BGPink3

[BGPink3Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGP3Color18#,#BGPink3Alpha#
 Group=BGPink3




;=====Buttons====
[BGPink3Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]

[BGPink3Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGPink3Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGP3Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGPink3][!SetOption BGColorCheck ImageAlpha #*BGPink3Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGP3Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGPink3][!WriteKeyValue BGColorCheck ImageAlpha #*BGPink3Alpha*#]