[BGRed2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color1#,#BGRed2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGRed2

[BGRed2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color2#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color3#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color4#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color5#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color6#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color7#,#BGRed2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGRed2

[BGRed2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color8#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color9#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color10#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color11#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color12#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color13#,#BGRed2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGRed2

[BGRed2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color14#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color15#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color16#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color17#,#BGRed2Alpha#
 Group=BGRed2

[BGRed2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR2Color18#,#BGRed2Alpha#
 Group=BGRed2




;=====Buttons=====
[BGRed2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]

[BGRed2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed2][!SetOption BGColorCheck ImageAlpha #*BGRed2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed2][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed2Alpha*#]