[BGRed1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color1#,#BGRed1Alpha#
 X=38
 Y=128
 Group=BGRed1

[BGRed1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color2#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color3#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color4#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color5#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color6#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color7#,#BGRed1Alpha#
 X=38
 Y=R
 Group=BGRed1

[BGRed1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color8#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color9#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color10#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color11#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color12#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color13#,#BGRed1Alpha#
 X=38
 Y=R
 Group=BGRed1

[BGRed1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color14#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color15#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color16#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color17#,#BGRed1Alpha#
 Group=BGRed1

[BGRed1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGR1Color18#,#BGRed1Alpha#
 Group=BGRed1




;=====Buttons=====
[BGRed1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]

[BGRed1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGRed1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGR1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGRed1][!SetOption BGColorCheck ImageAlpha #*BGRed1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGR1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGRed1][!WriteKeyValue BGColorCheck ImageAlpha #*BGRed1Alpha*#]