[BGYellow1Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color1#,#BGYellow1Alpha#
 X=38
 Y=128
 Group=BGYellow1

[BGYellow1Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color2#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color3#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color4#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color5#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color6#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color7#,#BGYellow1Alpha#
 X=38
 Y=R
 Group=BGYellow1

[BGYellow1Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color8#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color9#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color10#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color11#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color12#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color13#,#BGYellow1Alpha#
 X=38
 Y=R
 Group=BGYellow1

[BGYellow1Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color14#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color15#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color16#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color17#,#BGYellow1Alpha#
 Group=BGYellow1

[BGYellow1Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY1Color18#,#BGYellow1Alpha#
 Group=BGYellow1




;=====Buttons=====
[BGYellow1Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=128
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=38
 Y=R
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]

[BGYellow1Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow1Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY1Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow1][!SetOption BGColorCheck ImageAlpha #*BGYellow1Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY1Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow1][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow1Alpha*#]