[BGYellow2Color1]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color1#,#BGYellow2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGYellow2

[BGYellow2Color2]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color2#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color3]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color3#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color4]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color4#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color5]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color5#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color6]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color6#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color7]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color7#,#BGYellow2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGYellow2

[BGYellow2Color8]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color8#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color9]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color9#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color10]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color10#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color11]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color11#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color12]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color12#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color13]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color13#,#BGYellow2Alpha#
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGYellow2

[BGYellow2Color14]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color14#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color15]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color15#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color16]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color16#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color17]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color17#,#BGYellow2Alpha#
 Group=BGYellow2

[BGYellow2Color18]
 Meter=Image
 MeterStyle=ColorStyle
 SolidColor=#BGY2Color18#,#BGYellow2Alpha#
 Group=BGYellow2




;=====Buttons=====
[BGYellow2Color1B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=128
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color1#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color1#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color2B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color2#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color2#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color3B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color3#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color3#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color4B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color4#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color4#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color5B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color5#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color5#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color6B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color6#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 1][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color6#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 1][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color7B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color7#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color7#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color8B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color8#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color8#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color9B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color9#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color9#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color10B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color10#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color10#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color11B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color11#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color11#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color12B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color12#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 2][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color12#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 2][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color13B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 X=(#WORKAREAWIDTH#-307)
 Y=R
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color13#"][!SetVariable BGColorRow 1][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color13#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 1][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color14B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color14#"][!SetVariable BGColorRow 2][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color14#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 2][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color15B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color15#"][!SetVariable BGColorRow 3][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color15#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 3][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color16B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color16#"][!SetVariable BGColorRow 4][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color16#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 4][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color17B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color17#"][!SetVariable BGColorRow 5][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color17#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 5][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]

[BGYellow2Color18B]
 Meter=Image
 MeterStyle=ColorStyleButtons
 SolidColor=0,0,0,0
 Group=BGYellow2Buttons
 LeftMouseUpAction=[!SetVariable BackgroundColor "#BGY2Color18#"][!SetVariable BGColorRow 6][!SetVariable BGColorColumn 3][!SetVariable BGColorCheckGroup BGYellow2][!SetOption BGColorCheck ImageAlpha #*BGYellow2Alpha*#][!Update][!WriteKeyValue Variables BackgroundColor "#BGY2Color18#" "#@#Variables.inc"][!WriteKeyValue Variables BGColorRow 6][!WriteKeyValue Variables BGColorColumn 3][!WriteKeyValue Variables BGColorCheckGroup BGYellow2][!WriteKeyValue BGColorCheck ImageAlpha #*BGYellow2Alpha*#]